apiVersion: v1
kind: Service
metadata:
  name: grafana-lite-service
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    app: grafana-lite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
