apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::522814726044:user/terraform-admin
      username: terraform-admin
      groups:
        - system:masters
