name: CI - payment-service

on:
  push:
    paths:
      - 'payment-service/**'
  pull_request:
    paths:
      - 'payment-service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./payment-service
          file: ./payment-service/Dockerfile
          push: true
          tags: omkale23/payment-service:latest
      - name: Trigger ArgoCD sync
        run: |
          curl -X POST ${{ secrets.ARGOCD_WEBHOOK_URL }}
