apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-service
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-charts/payment-service
    repoURL: https://github.com/omkale23/cloud-native-app.git
    targetRevision: main
    helm:
      releaseName: payment-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
